# Practical No.3 (Question 1)

In [1]:
#IMPORTING LIBRARIES
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\MMANTC-MC-03\AppData\Local\Temp\ipykernel_7012\3256497564.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
#LOADING DATASET
df = pd.read_csv("income.csv")

In [3]:
df

                Name  Age  Income
0       Shane Willis   49   29552
1      Alexa Walters   32   63507
2       Colson Trejo   38   48746
3      Rosalyn Logan   42   52392
4     Rocco Caldwell   79   36283
..               ...  ...     ...
96        Theo Rojas   55   76157
97   Adaline Rodgers   79   40923
98   Mathias Nielsen   34   57345
99   Adelaide Dawson   54   75998
100  Khizar Karawita   87   16515

[101 rows x 3 columns]

In [4]:
df.describe()

              Age        Income
count  101.000000    101.000000
mean    50.792079  57699.693069
std     19.358883  22272.705811
min     20.000000  16515.000000
25%     32.000000  38123.000000
50%     52.000000  54714.000000
75%     68.000000  78441.000000
max     87.000000  98821.000000

In [5]:
#GROUPING AGE AND STORING IN A VARIBALE
grouped_data = df.groupby('Age')

In [6]:
#PRINTING THE VARIABLE BY ITERATION
for age, group in grouped_data:
    print("Age:", age)
    print(group)

Age: 20
                  Name  Age  Income
40           Hugh Howe   20   81459
55     Lylah Jaramillo   20   25982
75    Paisleigh Rangel   20   89414
76        Saint Hansen   20   25520
80  Muhammad Jefferson   20   74330
Age: 21
               Name  Age  Income
57  Emmeline Dawson   21   33056
58      Iker Carter   21   64382
Age: 23
           Name  Age  Income
23  Winter Mann   23   39540
Age: 24
                Name  Age  Income
38    Matias Sweeney   24   31173
41  Persephone Simon   24   33330
63    Delilah Person   24   61991
77       Hope Morris   24   63539
Age: 26
               Name  Age  Income
45      Reina Johns   26   53273
54  Genesis Houston   26   30377
Age: 27
                Name  Age  Income
8   Guillermo Greene   27   59609
10       Bode Monroe   27   40690
13     Raina Dejesus   27   34754
Age: 28
              Name  Age  Income
14      Rio Sierra   28   58755
26  Oakley Simpson   28   32648
43   Coraline Shah   28   61812
88   Lewis Vasquez   28   32291
Age: 29
              Name  Age  Income
11  Carly Esquivel   29   59178
Age: 31
               Name  Age  Income
81  Julieta Preston   31   48582
Age: 32
              Name  Age  Income
1    Alexa Walters   32   63507
33   Karen McCarty   32   95492
53  Angelica Bravo   32   69091
Age: 33
             Name  Age  Income
22  Brian Navarro   33   30556
Age: 34
               Name  Age  Income
98  Mathias Nielsen   34   57345
Age: 35
            Name  Age  Income
37  Meilani Lane   35   81535
60  Bodhi Morrow   35   51200
Age: 36
             Name  Age  Income
30  Trenton Casey   36   72442
Age: 38
             Name  Age  Income
2    Colson Trejo   38   48746
20  Saul Humphrey   38   78441
Age: 40
              Name  Age  Income
29  Lauryn Randall   40   50249
Age: 42
              Name  Age  Income
3    Rosalyn Logan   42   52392
6        John Dyer   42   33580
15  Marceline Lynn   42   94534
Age: 43
                   Name  Age  Income
24  Nehemiah Livingston   43   88589
56         Riggs Bernal   43   33254
Age: 44
              Name  Age  Income
35     Jimena Hale   44   40896
84  Dorian Jimenez   44   85911
Age: 45
           Name  Age  Income
79  Naya Curtis   45   36930
Age: 46
            Name  Age  Income
42   Zayne Hodge   46   54714
52  Forrest Shah   46   45384
64    Moses Sosa   46   70232
Age: 47
              Name  Age  Income
72  Dangelo Lucero   47   94719
Age: 48
               Name  Age  Income
12  Bridger Ellison   48   98821
89     Rose Mendoza   48   49898
Age: 49
           Name  Age  Income
0  Shane Willis   49   29552
Age: 51
                Name  Age  Income
36  Ezequiel Sampson   51   40516
Age: 52
              Name  Age  Income
73   Ila Whitehead   52   57511
83  Paulina Bowers   52   81785
Age: 54
               Name  Age  Income
78   Christian Moon   54   41114
99  Adelaide Dawson   54   75998
Age: 55
           Name  Age  Income
21  Journi Sims   55   91629
96   Theo Rojas   55   76157
Age: 56
             Name  Age  Income
61  Reyna Hampton   56   84016
Age: 57
            Name  Age  Income
28  Sawyer Wiley   57   28898
Age: 58
           Name  Age  Income
91  Paige Henry   58   93046
Age: 59
               Name  Age  Income
50  Hunter Morrison   59   97483
Age: 60
                 Name  Age  Income
86  Yehuda Villanueva   60   92818
Age: 61
            Name  Age  Income
69  Katie Stokes   61   64520
74    Zayd Felix   61   72398
Age: 62
                Name  Age  Income
16  Zechariah Potter   62   56112
Age: 63
              Name  Age  Income
39  Yara Macdonald   63   37281
Age: 64
                Name  Age  Income
49    Bellamy Morgan   64   30632
65  Cassandra Hebert   64   27141
Age: 65
          Name  Age  Income
67  Alma Hurst   65   38253
Age: 66
              Name  Age  Income
32     Talon Weeks   66   34086
44      Zain Greer   66   45674
46  Joziah Brennan   66   86097
Age: 67
              Name  Age  Income
70     Santana Ray   67   83507
87  Monroe Parsons   67   88575
Age: 68
                 Name  Age  Income
18        Jamie Rosas   68   51867
25    Milena Calderon   68   55825
66  Guillermo Cochran   68   38123
68        Neil Ingram   68   94998
Age: 69
           Name  Age  Income
62  Hank Morgan   69   52445
Age: 70
               Name  Age  Income
31    Sylvia Gaines   70   69643
34    Blaise Suarez   70   93627
51  Rebecca Hubbard   70   35014
Age: 72
            Name  Age  Income
9   Selena Morse   72   56718
59    Lucy Walsh   72   48881
Age: 73
              Name  Age  Income
17      Rory Russo   73   44323
48  Zayn Oâ€™Donnell   73   62500
71    Ruth Peralta   73   83105
Age: 74
             Name  Age  Income
5   Evelynn Clark   74   25821
47  Elodie Cortez   74   42104
95   Tessa Palmer   74   34847
Age: 75
               Name  Age  Income
19   Joelle Flowers   75   41182
82  Vincenzo Herman   75   92176
85    Adeline House   75   82922
94  Jovanni Garrett   75   81377
Age: 76
              Name  Age  Income
92  Carlos Douglas   76   35565
Age: 77
                Name  Age  Income
93  Aniyah Oâ€™Connell   77   58994
Age: 78
               Name  Age  Income
7   Estrella Hebert   78   51103
90       Dominic Li   78   85453
Age: 79
                Name  Age  Income
4     Rocco Caldwell   79   36283
27  Anastasia Jordan   79   46393
97   Adaline Rodgers   79   40923
Age: 87
                Name  Age  Income
100  Khizar Karawita   87   16515

In [7]:
#CALCULATING SUMMARY STATISTICS FOR THE 'INCOME' VARIABLE WITHIN EACH GROUP OF THE DATAFRAMEGROUPBY OBJECT GROUPED_DATA.
summary_stats = grouped_data.describe()

In [8]:
summary_stats

    Income                                                                    \
     count          mean           std      min       25%      50%       75%
Age
20     5.0  59341.000000  31124.525282  25520.0  25982.00  74330.0  81459.00
21     2.0  48719.000000  22150.827027  33056.0  40887.50  48719.0  56550.50
23     1.0  39540.000000           NaN  39540.0  39540.00  39540.0  39540.00
24     4.0  47508.250000  17650.289504  31173.0  32790.75  47660.5  62378.00
26     2.0  41825.000000  16189.916862  30377.0  36101.00  41825.0  47549.00
27     3.0  45017.666667  12980.342073  34754.0  37722.00  40690.0  50149.50
28     4.0  46376.500000  16107.502858  32291.0  32558.75  45701.5  59519.25
29     1.0  59178.000000           NaN  59178.0  59178.00  59178.0  59178.00
31     1.0  48582.000000           NaN  48582.0  48582.00  48582.0  48582.00
32     3.0  76030.000000  17084.271919  63507.0  66299.00  69091.0  82291.50
33     1.0  30556.000000           NaN  30556.0  30556.00  30556.0  30556.00
34     1.0  57345.000000           NaN  57345.0  57345.00  57345.0  57345.00
35     2.0  66367.500000  21450.084207  51200.0  58783.75  66367.5  73951.25
36     1.0  72442.000000           NaN  72442.0  72442.00  72442.0  72442.00
38     2.0  63593.500000  20997.535867  48746.0  56169.75  63593.5  71017.25
40     1.0  50249.000000           NaN  50249.0  50249.00  50249.0  50249.00
42     3.0  60168.666667  31212.256204  33580.0  42986.00  52392.0  73463.00
43     2.0  60921.500000  39127.753737  33254.0  47087.75  60921.5  74755.25
44     2.0  63403.500000  31830.411755  40896.0  52149.75  63403.5  74657.25
45     1.0  36930.000000           NaN  36930.0  36930.00  36930.0  36930.00
46     3.0  56776.666667  12551.761682  45384.0  50049.00  54714.0  62473.00
47     1.0  94719.000000           NaN  94719.0  94719.00  94719.0  94719.00
48     2.0  74359.500000  34593.785056  49898.0  62128.75  74359.5  86590.25
49     1.0  29552.000000           NaN  29552.0  29552.00  29552.0  29552.00
51     1.0  40516.000000           NaN  40516.0  40516.00  40516.0  40516.00
52     2.0  69648.000000  17164.310007  57511.0  63579.50  69648.0  75716.50
54     2.0  58556.000000  24666.712955  41114.0  49835.00  58556.0  67277.00
55     2.0  83893.000000  10940.356119  76157.0  80025.00  83893.0  87761.00
56     1.0  84016.000000           NaN  84016.0  84016.00  84016.0  84016.00
57     1.0  28898.000000           NaN  28898.0  28898.00  28898.0  28898.00
58     1.0  93046.000000           NaN  93046.0  93046.00  93046.0  93046.00
59     1.0  97483.000000           NaN  97483.0  97483.00  97483.0  97483.00
60     1.0  92818.000000           NaN  92818.0  92818.00  92818.0  92818.00
61     2.0  68459.000000   5570.587222  64520.0  66489.50  68459.0  70428.50
62     1.0  56112.000000           NaN  56112.0  56112.00  56112.0  56112.00
63     1.0  37281.000000           NaN  37281.0  37281.00  37281.0  37281.00
64     2.0  28886.500000   2468.509773  27141.0  28013.75  28886.5  29759.25
65     1.0  38253.000000           NaN  38253.0  38253.00  38253.0  38253.00
66     3.0  55285.666667  27305.203393  34086.0  39880.00  45674.0  65885.50
67     2.0  86041.000000   3583.617167  83507.0  84774.00  86041.0  87308.00
68     4.0  60203.250000  24405.424293  38123.0  48431.00  53846.0  65618.25
69     1.0  52445.000000           NaN  52445.0  52445.00  52445.0  52445.00
70     3.0  66094.666667  29467.167226  35014.0  52328.50  69643.0  81635.00
72     2.0  52799.500000   5541.595844  48881.0  50840.25  52799.5  54758.75
73     3.0  63309.333333  19403.663219  44323.0  53411.50  62500.0  72802.50
74     3.0  34257.333333   8157.499760  25821.0  30334.00  34847.0  38475.50
75     4.0  74414.250000  22662.185102  41182.0  71328.25  82149.5  85235.50
76     1.0  35565.000000           NaN  35565.0  35565.00  35565.0  35565.00
77     1.0  58994.000000           NaN  58994.0  58994.00  58994.0  58994.00
78     2.0  68278.000000  24289.117934  51103.0  59690.50  68278.0  76865.50
79     3.0  41199.666667   5060.675186  36283.0  38603.00  40923.0  43658.00
87     1.0  16515.000000           NaN  16515.0  16515.00  16515.0  16515.00


         max
Age
20   89414.0
21   64382.0
23   39540.0
24   63539.0
26   53273.0
27   59609.0
28   61812.0
29   59178.0
31   48582.0
32   95492.0
33   30556.0
34   57345.0
35   81535.0
36   72442.0
38   78441.0
40   50249.0
42   94534.0
43   88589.0
44   85911.0
45   36930.0
46   70232.0
47   94719.0
48   98821.0
49   29552.0
51   40516.0
52   81785.0
54   75998.0
55   91629.0
56   84016.0
57   28898.0
58   93046.0
59   97483.0
60   92818.0
61   72398.0
62   56112.0
63   37281.0
64   30632.0
65   38253.0
66   86097.0
67   88575.0
68   94998.0
69   52445.0
70   93627.0
72   56718.0
73   83105.0
74   42104.0
75   92176.0
76   35565.0
77   58994.0
78   85453.0
79   46393.0
87   16515.0

# Practical No.3 (Question 2)

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
df_iris = pd.read_csv('Iris.csv')

In [15]:
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [22]:
df_iris['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [31]:
setosa = df_iris[df_iris.iloc[:, -1] == 'Iris-setosa']

In [32]:
setosa

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [36]:
versicolor = df_iris[df_iris.iloc[:, -1] == 'Iris-versicolor']

In [37]:
versicolor

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor
89,90,5.5,2.5,4.0,1.3,Iris-versicolor
90,91,5.5,2.6,4.4,1.2,Iris-versicolor
91,92,6.1,3.0,4.6,1.4,Iris-versicolor
92,93,5.8,2.6,4.0,1.2,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor
94,95,5.6,2.7,4.2,1.3,Iris-versicolor
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor

In [39]:
virginica = df_iris[df_iris.iloc[ : , -1] == 'Iris-virginica']

In [40]:
virginica

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica